#!/usr/bin/env python3
"""Rebuild .specs/INDEX.md, DECISIONS.md and OPEN-QUESTIONS.md from the spec tree, report drift.

Stdlib only — no pyyaml, no install step. Handles the subset of YAML the spec
frontmatter contract uses: scalars, inline lists, and block lists.

Three generated files, answering three questions, deliberately separate because they are read at
different moments and a reader shouldn't pay for the ones they don't need:

INDEX.md is a routing table: code path -> owning spec. Read every session, so everything in it is
what you need *to route* — coverage gaps and violations appear only as counts, with the
item-by-item lists left to this script's own stdout.

DECISIONS.md aggregates what was decided and what lost. Read before proposing an approach: a
decision's rejected alternatives leave no trace in the source, so this is content no amount of
code reading recovers, and it is scattered one entry at a time at the bottom of whichever spec
owns the file. INDEX.md can't route anyone to it, because a decision often isn't about a code path.

OPEN-QUESTIONS.md holds what nobody has decided yet — the other thing missing from the code, but
scoped to whoever touches the spec that raised it rather than to every task, and typically the
faster-growing of the two.

All three are helpers: when one disagrees with the specs, the specs win.

Every spec has `status:` in its frontmatter: `draft` (not agreed yet), `approved` (agreed, OK to
build) or `merged` (describes the code as it is). Specs outside `changes/` are `merged`.

Open changes under `.specs/changes/` are read too. Any folder there directly holding a
`specs.<path>.md` file is a change, at any depth — nesting only groups, and a folder can be a change
and hold changes. Each `specs.<path>.md` is a whole spec as it should read afterwards, landing at
`.specs/<path>`: a new spec, or the spec moved there from `.specs/<path>` with `git mv`, edited — so
`.specs/<path>` itself is gone while the change is open. Approval is per spec file, by its `status:`;
a change is Draft, Approved, or Partly approved. Its `## Change` section is prose and never parsed.
INDEX.md lists open changes and routes a spec's code to the change holding it; DECISIONS.md and
OPEN-QUESTIONS.md include the specs in open changes.

A spec's `## Behaviour` is one bullet per rule; a rule the code breaks today carries a
`Currently violated:` sub-bullet, which INDEX.md counts. The rules themselves are never checked here:
the tests are their proof, found through `owns`.

Usage:
    python3 build_index.py [--specs-dir .specs] [--repo-root <path>] [--check]

--check exits 1 only on structural drift: a file with no frontmatter or no `id`/`title`, no single
root spec, a dangling `owns` glob, an unknown `parent`/`related`, a duplicate id, ambiguous ownership,
a parent cycle, and a change spec file that can't land where it's named. Everything else — warnings
(a missing or misplaced `status` among them), out-of-date generated files, coverage gaps,
possibly-stale specs — is reported and never fails: the generated files are kept out of git.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Directories never reported as "unowned". Build output, tooling, and the agent setup itself.
# Skipping only affects unowned-reporting — routing is unaffected either way.
SKIP_DIRS = {
    "node_modules", "build", "dist", "out", "target", "vendor", "__pycache__", "venv", "coverage",
    # Not source: the Gradle wrapper and prebuilt `.aar`/`.jar` drops. A spec can own behaviour, not a
    # binary, so reporting these as uncovered only adds noise. Dot folders are skipped wherever this is.
    "gradle", "libs",
}

# This script's own output. Never parsed as specs — they have no frontmatter, and reading them
# back in would report each one as a malformed spec.
GENERATED = {"INDEX.md", "DECISIONS.md", "OPEN-QUESTIONS.md"}
# Markdown under `.specs/` that isn't a spec.
NOT_SPECS = GENERATED | {"README.md"}
# A manual test plan kept beside the spec it tests: `<spec>.manual-test-plan.md`.
TEST_PLAN_SUFFIX = ".manual-test-plan.md"

HEADER = """<!-- Generated by spec-rebuild-overviews — regenerate rather than edit; when this disagrees with the specs, the specs win. -->
<!-- Regenerate: python3 .agents/skills/spec-rebuild-overviews/scripts/build_index.py -->"""

# Open changes live here. Parsed by load_changes, never as specs.
CHANGES = "changes"
# A change's spec file, named after where it lands in `.specs/`: `specs.feature.logger.md`.
CHANGE_SPEC = re.compile(r"^specs\.(.+)\.md$")
STATUSES = ("draft", "approved", "merged")


@dataclass
class Decision:
    """One entry under a spec's `## Decisions`, parsed into its labelled sub-bullets.

    The shape is spec-style-rules' *What was rejected*'s: a bolded choice, then `Instead of` / `Because` /
    `Revisit when` / `Replaced {date}:` as sub-bullets. `instead_of` is the one that carries the
    information the code can't show — an entry missing it usually isn't a decision at all, which
    is why it's reported rather than quietly rendered blank.
    """
    text: str
    instead_of: str = ""
    because: str = ""
    revisit_when: str = ""
    replaced: str = ""
    replaced_date: str = ""


@dataclass
class OpenQuestion:
    text: str
    action: str
    resolved: bool = False


@dataclass
class Spec:
    path: Path
    id: str
    title: str
    parent: str | None
    owns: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)
    updated: str = ""
    decisions: list[Decision] = field(default_factory=list)
    questions: list[OpenQuestion] = field(default_factory=list)
    # `Currently violated:` lines under Behaviour, as "rule — violation".
    violations: list[str] = field(default_factory=list)
    # Change history rows too long to be one sentence, as "ticket date (n words)".
    long_history_rows: list[str] = field(default_factory=list)


# --------------------------------------------------------------------------- parsing


def split_frontmatter(text: str) -> str | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    return text[3:end]


def unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_frontmatter(block: str) -> dict[str, object]:
    """Minimal YAML: `key: scalar`, `key: [a, b]`, and block lists under `key:`."""
    data: dict[str, object] = {}
    current_key: str | None = None

    for raw in block.splitlines():
        line = re.sub(r"""^((?:[^#"']|"[^"]*"|'[^']*')*?)\s+#.*$""", r"\1", raw.rstrip())  # an inline `# comment`
        if not line.strip() or line.strip().startswith("#"):
            continue

        stripped = line.lstrip()
        indented = len(line) - len(stripped)

        if stripped.startswith("- ") and current_key and indented > 0:
            data.setdefault(current_key, [])
            target = data[current_key]
            if isinstance(target, list):
                target.append(unquote(stripped[2:]))
            continue

        if ":" not in stripped:
            continue

        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        current_key = key

        if not value:
            data[key] = []
        elif value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[key] = [unquote(p) for p in inner.split(",") if p.strip()] if inner else []
        else:
            data[key] = unquote(value)

    return data


def as_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(v) for v in value if str(v).strip()]
    if isinstance(value, str) and value.strip() and value.strip() != "[]":
        return [value.strip()]
    return []


def scalar(value: object) -> str:
    """A frontmatter value as a string; an empty `key:` parses as [] and reads as ""."""
    return value.strip() if isinstance(value, str) else ""


def parent_of(meta: dict[str, object]) -> str | None:
    parent = meta.get("parent")
    return None if parent in (None, "", "null", "~", []) else str(parent)


BOLD = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)
ACTION = re.compile(r"\*\*Action:\*\*\s*(.*)", re.DOTALL)


def squash(text: str) -> str:
    """Collapse a multi-line markdown span into one line, dropping list/emphasis punctuation."""
    return " ".join(text.replace("~~", "").split()).strip(" —-–")


def body_after_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    return text[end + 4:] if end != -1 else text


def extract_section(body: str, heading: str) -> str:
    """The lines under a `## heading`, up to the next heading of the same or higher level."""
    lines = body.splitlines()
    wanted = heading.strip().lower()
    out: list[str] = []
    collecting = False

    for line in lines:
        if line.startswith("## "):
            if collecting:
                break
            collecting = line[3:].strip().lower() == wanted
            continue
        if line.startswith("# ") and collecting:
            break
        if collecting:
            out.append(line)

    return "\n".join(out)


def iter_entries(section: str) -> list[str]:
    """Top-level `- ` bullets, each joined with its indented continuation lines.

    A decision or an open question routinely wraps across several lines, and its bolded span can
    wrap with it — so entries have to be reassembled before anything can be matched against them.
    """
    entries: list[str] = []
    current: list[str] = []

    for line in section.splitlines():
        starts_entry = line.startswith("- ")
        if starts_entry:
            if current:
                entries.append("\n".join(current))
            current = [line[2:]]
        elif current and (not line.strip() or line.startswith((" ", "\t"))):
            current.append(line)
        elif current:
            entries.append("\n".join(current))
            current = []

    if current:
        entries.append("\n".join(current))

    return [e for e in entries if e.strip()]


SUBFIELD = re.compile(r"^\s+-\s*\*\*(.+?)\*\*\s*(.*)$")


def split_fields(entry: str) -> tuple[str, dict[str, str]]:
    """Split an entry into its headline and its labelled sub-bullets.

    Both the headline and a field's value can wrap across lines, so this tracks which one is
    currently open rather than assuming one line each.
    """
    head: list[str] = []
    fields: dict[str, str] = {}
    label: str | None = None
    buf: list[str] = []

    for line in entry.splitlines():
        match = SUBFIELD.match(line)
        if match:
            if label is not None:
                fields[label] = squash(" ".join(buf))
            label = match.group(1).strip().rstrip(":").lower()
            buf = [match.group(2)]
        elif label is not None:
            buf.append(line)
        else:
            head.append(line)

    if label is not None:
        fields[label] = squash(" ".join(buf))

    bold = BOLD.search("\n".join(head))
    headline = squash(bold.group(1)) if bold else squash("\n".join(head))
    return headline, fields


def parse_decisions(body: str) -> list[Decision]:
    out: list[Decision] = []
    for entry in iter_entries(extract_section(body, "Decisions")):
        text, fields = split_fields(entry)
        if not text:
            continue

        # `Replaced` carries its date inside the label (`**Replaced 2026-09-10:**`), so the key
        # varies per entry and can't be looked up directly.
        replaced_key = next((k for k in fields if k.startswith("replaced")), "")
        replaced_date = replaced_key[len("replaced"):].strip() if replaced_key else ""

        out.append(
            Decision(
                text=text,
                instead_of=fields.get("instead of", ""),
                because=fields.get("because", ""),
                revisit_when=fields.get("revisit when", ""),
                replaced=fields.get(replaced_key, "") if replaced_key else "",
                replaced_date=replaced_date,
            )
        )
    return out


def parse_open_questions(body: str) -> list[OpenQuestion]:
    out: list[OpenQuestion] = []
    for entry in iter_entries(extract_section(body, "Open questions")):
        stripped = entry.lstrip()
        if not stripped.startswith("["):
            continue
        resolved = stripped[:3].lower() == "[x]"
        match = BOLD.search(entry)
        text = squash(match.group(1)) if match else squash(stripped[3:])
        action_match = ACTION.search(entry)
        action = squash(action_match.group(1)) if action_match else ""
        if text:
            out.append(
                OpenQuestion(text=text, action=action, resolved=resolved)
            )
    return out


BULLET = re.compile(r"^(\s*)-\s+(.*)$")
VIOLATED = re.compile(r"^(\s*)-\s+(?:\*\*)?Currently violated:?(?:\*\*)?:?\s*(.*)$", re.IGNORECASE)


def indent(line: str) -> int:
    return len(line) - len(line.lstrip())


def parse_violations(body: str) -> list[str]:
    """`Currently violated:` sub-bullets under `## Behaviour`, as "rule — violation".

    A violation is the one line in a spec that goes false the moment someone fixes the code, and
    nothing about the fix points back at it — a spec edited after the code still looks fresh.
    Counting them in INDEX.md is what gets them re-read. The rule is the nearest bullet above it
    with less indent, so lines grouped under bold labels read the same as a flat list.
    """
    lines = extract_section(body, "Behaviour").splitlines()
    out: list[str] = []
    for i, line in enumerate(lines):
        match = VIOLATED.match(line)
        if not match:
            continue
        depth = len(match.group(1))
        # The violation's own text, with any lines it wraps onto.
        end = i + 1
        while end < len(lines) and lines[end].strip() and indent(lines[end]) > depth \
                and not BULLET.match(lines[end]):
            end += 1
        violation = squash(" ".join([match.group(2)] + lines[i + 1:end]))
        # The rule it sits under, with any lines that rule wraps onto.
        start = next((j for j in range(i - 1, -1, -1)
                      if BULLET.match(lines[j]) and indent(lines[j]) < depth), None)
        rule = ""
        if start is not None:
            head = [BULLET.match(lines[start]).group(2)]
            head += [l for l in lines[start + 1:i] if l.strip() and not BULLET.match(l)]
            rule = squash(" ".join(head))
        out.append(f"{rule} — {violation}" if rule else violation)
    return out


# spec-style-rules' *One row, one sentence*. Past this, a row is almost always a root-cause write-up or
# an investigation log rather than a statement of what changed.
HISTORY_ROW_WORDS = 35


def parse_long_history_rows(body: str) -> list[str]:
    """Change history rows whose Change cell runs past what one sentence needs.

    The style rule broken most often in practice, and the only one a word count can see.
    Informational: a long row misleads nobody, it taxes every reader.
    """
    out: list[str] = []
    for line in extract_section(body, "Change history").splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or set(cells[1]) <= set("-: ") or cells[1].lower() == "change":
            continue
        words = len(cells[1].split())
        if words > HISTORY_ROW_WORDS:
            out.append(f"{cells[0]} {cells[-1]} ({words} words)")
    return out


def load_specs(specs_dir: Path) -> tuple[list[Spec], list[str], list[str]]:
    """Every spec under `.specs/` outside `changes/`, plus (drift, warnings) found reading them."""
    specs: list[Spec] = []
    problems: list[str] = []
    warnings: list[str] = []

    for path in sorted(specs_dir.rglob("*.md")):
        if (path.name in NOT_SPECS or path.name.endswith(TEST_PLAN_SUFFIX)
                or path.relative_to(specs_dir).parts[0] == CHANGES):
            continue

        text = path.read_text(encoding="utf-8")
        block = split_frontmatter(text)
        rel = path.relative_to(specs_dir.parent).as_posix()

        if block is None:
            problems.append(f"{rel}: no frontmatter block — every spec needs one")
            continue

        meta = parse_frontmatter(block)
        missing = [k for k in ("id", "title") if not meta.get(k)]
        if missing:
            problems.append(f"{rel}: frontmatter missing required key(s): {', '.join(missing)}")
            continue
        status = scalar(meta.get("status"))
        if not status:
            warnings.append(f"{rel}: no status — add `status: merged`")
        elif status in ("draft", "approved"):
            warnings.append(f"{rel}: is `{status}` but sits outside changes/ — a spec in progress "
                            f"belongs in a change")
        elif status != "merged":
            warnings.append(f"{rel}: unknown status `{status}` — use `merged` outside changes/")

        spec_id = str(meta["id"])
        body = body_after_frontmatter(text)

        specs.append(
            Spec(
                path=path,
                id=spec_id,
                title=str(meta["title"]),
                parent=parent_of(meta),
                owns=as_list(meta.get("owns")),
                related=as_list(meta.get("related")),
                updated=scalar(meta.get("updated")),
                decisions=parse_decisions(body),
                questions=parse_open_questions(body),
                violations=parse_violations(body),
                long_history_rows=parse_long_history_rows(body),
            )
        )

    return specs, problems, warnings


# --------------------------------------------------------------------------- changes

ROOT_SPEC = re.compile(r"^\d\d-[^/]+\.md$")


def change_spec_rel(name: str) -> str:
    """`specs.feature.logger.md` → `feature/logger.md`: where a change's spec file lands in `.specs/`."""
    match = CHANGE_SPEC.match(name)
    return match.group(1).replace(".", "/") + ".md" if match else ""


@dataclass
class ChangeSpec:
    """One `specs.<path>.md` file in a change folder: the whole spec as it should read afterwards,
    landing at `.specs/<path>` (dots for slashes).

    `landing` is a spec still at that path — drift, since a change moves the spec it edits.
    """
    rel: str
    file: str
    spec_id: str = ""
    title: str = ""
    parent: str | None = None
    has_parent_key: bool = False
    status: str = ""
    owns: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)
    decisions: list[Decision] = field(default_factory=list)
    questions: list[OpenQuestion] = field(default_factory=list)
    landing: Spec | None = None

    @property
    def new(self) -> bool:
        return self.landing is None

    @property
    def approved(self) -> bool:
        # `merged` in a change is past approval; validate_changes warns it should merge.
        return self.status in ("approved", "merged")

    def pending_decisions(self) -> list[Decision]:
        """Its decisions — only those the spec still at its place lacks, when one is (drift)."""
        if self.landing is None:
            return self.decisions
        have = {d.text.lower() for d in self.landing.decisions}
        return [d for d in self.decisions if d.text.lower() not in have]

    def pending_questions(self) -> list[OpenQuestion]:
        """Open questions this file adds, the same way as pending_decisions."""
        have = {q.text.lower() for q in self.landing.questions} if self.landing else set()
        return [q for q in self.questions if not q.resolved and q.text.lower() not in have]


@dataclass
class Task:
    title: str
    done: bool


@dataclass(eq=False)
class Change:
    """A folder under `.specs/changes/` directly holding spec files, and an optional implementation plan."""
    path: Path
    name: str
    specs: list[ChangeSpec] = field(default_factory=list)
    tasks: list[Task] = field(default_factory=list)
    # The nearest enclosing change folder, when nested — for display only.
    parent: Change | None = field(default=None, repr=False)

    @property
    def approved(self) -> bool:
        return all(s.approved for s in self.specs)

    def status(self) -> str:
        done = sum(s.approved for s in self.specs)
        if done == len(self.specs):
            return "Approved"
        return "Draft" if done == 0 else f"Partly approved ({done}/{len(self.specs)})"

    def tasks_all_done(self) -> bool:
        return bool(self.tasks) and all(t.done for t in self.tasks)

    def link(self, specs_dir: Path) -> str:
        return self.path.relative_to(specs_dir).as_posix() + "/"


def parse_change_spec(path: Path, by_path: dict[str, Spec]) -> ChangeSpec:
    text = path.read_text(encoding="utf-8")
    meta = parse_frontmatter(split_frontmatter(text) or "")
    body = body_after_frontmatter(text)
    rel = change_spec_rel(path.name)
    spec_id = str(meta.get("id") or "")
    return ChangeSpec(
        rel=rel,
        file=path.name,
        spec_id=spec_id,
        title=str(meta.get("title") or ""),
        parent=parent_of(meta),
        has_parent_key="parent" in meta,
        status=scalar(meta.get("status")),
        owns=as_list(meta.get("owns")),
        related=as_list(meta.get("related")),
        decisions=parse_decisions(body),
        questions=parse_open_questions(body),
        landing=by_path.get(rel),
    )


PLAN = "implementation-plan.md"
TASK_LINE = re.compile(r"^\d+\.\s+\[([ xX])\]\s+(.*)$")


def parse_tasks(change: Change, text: str) -> None:
    """Numbered checkboxes under `## Tasks`. A task's headline may wrap onto indented lines; its
    `- Check:` sub-bullets and `>` notes aren't part of it."""
    body = body_after_frontmatter(text)
    section = extract_section(body, "Tasks") or body
    entries: list[tuple[bool, list[str]]] = []
    in_headline = False
    for line in section.splitlines():
        match = TASK_LINE.match(line)
        if match:
            entries.append((match.group(1).lower() == "x", [match.group(2)]))
            in_headline = True
        elif not in_headline:
            continue
        elif line.startswith((" ", "\t")) and line.strip() and not line.strip().startswith(("-", ">")):
            entries[-1][1].append(line.strip())
        else:
            in_headline = False
    for done, headline in entries:
        change.tasks.append(Task(title=squash(" ".join(headline)), done=done))


def load_change(folder: Path, root: Path, by_path: dict[str, Spec]) -> Change:
    change = Change(path=folder, name=folder.relative_to(root).as_posix())
    for path in sorted(p for p in folder.glob("specs.*.md") if p.is_file()):
        change.specs.append(parse_change_spec(path, by_path))
    plan = folder / PLAN
    if plan.is_file():
        parse_tasks(change, plan.read_text(encoding="utf-8"))
    return change


def load_changes(specs_dir: Path, specs: list[Spec]) -> tuple[list[Change], list[str]]:
    """Every open change, in folder order, plus warnings about change folders.

    A change is a folder directly holding at least one `specs.<path>.md`; any other folder only groups.
    """
    root = specs_dir / CHANGES
    if not root.is_dir():
        return [], []
    by_path = {s.path.relative_to(specs_dir).as_posix(): s for s in specs}
    changes: list[Change] = []
    warnings: list[str] = []

    def walk(folder: Path, enclosing: Change | None) -> None:
        current = enclosing
        rel = folder.relative_to(specs_dir.parent).as_posix()
        if folder != root and any(p.is_file() for p in folder.glob("specs.*.md")):
            current = load_change(folder, root, by_path)
            current.parent = enclosing
            changes.append(current)
        elif folder != root and (folder / PLAN).is_file():
            warnings.append(f"{rel}: no spec files yet — a change holds one `specs.<path>.md` per spec "
                            f"it touches")
        for sub in sorted(p for p in folder.iterdir() if p.is_dir()):
            walk(sub, current)

    walk(root, None)
    return changes, warnings


def validate_changes(
    changes: list[Change], by_id: dict[str, Spec], repo_root: Path
) -> tuple[list[str], list[str]]:
    """(drift, warnings) for open changes.

    Drift is only what stops a spec file from landing: a spec still at its place in `.specs/`, a
    path outside the tree, an unknown parent or related, a duplicate id.
    """
    errors: list[str] = []
    warnings: list[str] = []
    known = set(by_id) | {s.spec_id for c in changes for s in c.specs if s.spec_id}
    new_at: dict[str, list[tuple[str, str]]] = {}  # new spec id -> [(where, rel)]
    by_rel: dict[str, list[tuple[Change, ChangeSpec]]] = {}

    for change in changes:
        rel = change.path.relative_to(repo_root).as_posix()
        for spec in change.specs:
            where = f"{rel}/{spec.file}"
            if not spec.status:
                warnings.append(f"{where}: no status — add `status: draft`")
            elif spec.status == "merged":
                warnings.append(f"{where}: is `merged` but still in a change — merge it")
            elif spec.status not in STATUSES:
                warnings.append(f"{where}: unknown status `{spec.status}` — use `draft` or `approved`")
            if not spec.spec_id:
                errors.append(f"{where} has no `id:` — a spec file is the whole spec, id included")
                continue
            if not (spec.rel.startswith(("feature/", "contract/")) or ROOT_SPEC.match(spec.rel)):
                errors.append(f"{where} lands at .specs/{spec.rel}, which is not under feature/ or "
                              f"contract/, or a root spec")
            missing = [key for key, present in (("title", spec.title), ("parent", spec.has_parent_key))
                       if not present]
            if missing:
                warnings.append(f"{where} has no {' or '.join(f'`{k}:`' for k in missing)}")
            if spec.parent and spec.parent not in known:
                errors.append(f"{where}: parent '{spec.parent}' is not a known spec id")
            for ref in spec.related:
                if ref not in known:
                    errors.append(f"{where}: related '{ref}' is not a known spec id")
            if spec.landing is not None:
                errors.append(f"{where}: .specs/{spec.rel} is still there — a change moves the spec it "
                              f"edits with `git mv`, never copies it")
            else:
                if spec.spec_id in by_id:
                    other = by_id[spec.spec_id].path.relative_to(repo_root).as_posix()
                    errors.append(f"duplicate id '{spec.spec_id}': {where} and {other}")
                new_at.setdefault(spec.spec_id, []).append((where, spec.rel))
            by_rel.setdefault(spec.rel, []).append((change, spec))

    for spec_id, entries in sorted(new_at.items()):
        if len({r for _, r in entries}) > 1:
            errors.append(f"duplicate id '{spec_id}': {' and '.join(w for w, _ in entries)}")

    for rel, holders in sorted(by_rel.items()):
        if len(holders) < 2:
            continue
        names = " and ".join(f"`{c.name}`" for c, _ in holders)
        warnings.append(f"{names} both hold .specs/{rel} — fold one in first, then move it into the other")
    return errors, warnings


def spec_file_link(change: Change, spec: ChangeSpec, specs_dir: Path) -> str:
    return (change.path / spec.file).relative_to(specs_dir).as_posix()


def change_label(change: Change) -> str:
    """Top-level changes by name; a nested one by its path under the change enclosing it, indented."""
    if change.parent is None:
        return f"`{change.name}`"
    depth, cursor = 0, change.parent
    while cursor is not None:
        depth, cursor = depth + 1, cursor.parent
    return "&nbsp;&nbsp;" * (depth - 1) + f"↳ `{change.path.relative_to(change.parent.path).as_posix()}`"


def render_pending(changes: list[Change], specs_dir: Path) -> str:
    if not changes:
        return "_No open changes._"
    out = [
        "Work being written or agreed that `.specs/` doesn't show yet. Before editing code a listed "
        "spec owns, read its spec file in the change; its `implementation-plan.md` only when building "
        "the change. Status comes from each spec file's `status:`.",
        "",
        "| Change | Status | Specs | Tasks done |",
        "|---|---|---|---|",
    ]
    for change in changes:
        spec_cells = ", ".join(
            f"[`{s.spec_id or s.file}`]({spec_file_link(change, s, specs_dir)})"
            for s in change.specs
        ) or "—"
        done = f"{sum(t.done for t in change.tasks)}/{len(change.tasks)}" if change.tasks else "—"
        out.append(
            f"| [{change_label(change)}]({change.link(specs_dir)}) | {change.status()} | "
            f"{spec_cells} | {done} |"
        )
    return "\n".join(out)


# --------------------------------------------------------------------------- checks


def glob_specificity(pattern: str) -> tuple[int, int]:
    """Higher sorts first. Fewer wildcards and more path segments = more specific."""
    return (-pattern.count("*") - 2 * pattern.count("**"), pattern.count("/"))


def iter_files(root: Path):
    """Yield every file under root, pruning SKIP_DIRS and dotdirs without descending into them."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]
        for name in filenames:
            yield Path(dirpath) / name


def find_gaps(
    specs: list[Spec], repo_root: Path, extra: list[str], max_depth: int = 4
) -> list[str]:
    """Directories with zero spec coverage, found by actually checking which files match an
    `owns` glob — not by comparing directory name prefixes, which hides gaps nested under a
    directory that's only partially covered (e.g. `src/checkout/**` owned doesn't mean the rest
    of `src/` is; every sibling under `src/` needs checking individually).

    A directory with no coverage at all is reported and not descended into further (the whole
    subtree is the gap). A directory that's fully covered is skipped. A directory that's a mix
    gets descended into, to find exactly which subdirectories are the actual gap.
    """
    # `extra`: code an open change will own once its new spec exists — already routed, not a gap.
    owned_patterns = [p for s in specs for p in s.owns] + extra

    def covered(file_path: Path) -> bool:
        rel = file_path.relative_to(repo_root).as_posix()
        return any(fnmatch.fnmatch(rel, pat) for pat in owned_patterns)

    gaps: list[str] = []

    def classify(dir_path: Path, depth: int) -> None:
        rel_dir = dir_path.relative_to(repo_root).as_posix()
        all_files = list(iter_files(dir_path))
        if not all_files:
            return  # empty directory — nothing to own, nothing to report

        covered_count = sum(1 for f in all_files if covered(f))
        if covered_count == 0:
            gaps.append(f"'{rel_dir}/' has no owning spec yet")
            return
        if covered_count == len(all_files):
            return  # fully covered

        # Partially covered — descend to isolate the actual gap, unless we've gone deep enough
        # that further drilling stops being useful.
        if depth >= max_depth:
            gaps.append(f"'{rel_dir}/' is partially covered — check its subdirectories")
            return

        try:
            subdirs = sorted(
                e for e in dir_path.iterdir()
                if e.is_dir() and e.name not in SKIP_DIRS and not e.name.startswith(".")
            )
            loose_files = [e for e in dir_path.iterdir() if e.is_file()]
        except OSError:
            return

        for sub in subdirs:
            classify(sub, depth + 1)

        uncovered_loose = [f for f in loose_files if not covered(f)]
        if uncovered_loose:
            names = ", ".join(f.name for f in sorted(uncovered_loose)[:3])
            more = f" (+{len(uncovered_loose) - 3} more)" if len(uncovered_loose) > 3 else ""
            gaps.append(f"'{rel_dir}/' has uncovered file(s): {names}{more}")

    for child in sorted(repo_root.iterdir()):
        if child.is_dir() and not child.name.startswith(".") and child.name not in SKIP_DIRS:
            classify(child, 1)

    return gaps


# Above this, two decisions in different specs are near-certainly the same decision written twice.
# Tuned to catch rewordings ("Version negotiation stays in X, not in the API module" vs
# "Version-negotiation semantics stay in X, not here") without flagging two decisions that merely
# discuss the same module.
DUPLICATE_RATIO = 0.6


def find_decision_problems(specs: list[Spec]) -> list[str]:
    """Decisions that aren't decisions, and decisions owned by two specs at once.

    Both are informational. "No `Instead of`" is a strong hint the entry is really a Behaviour rule
    or a scope note, but judging that needs a human read. Duplication is a similarity heuristic, and
    the fix (which spec should own it) is never mechanical.
    """
    import difflib

    out: list[str] = []
    flat = [(s, d) for s in specs for d in s.decisions]

    for spec, decision in flat:
        if not decision.instead_of:
            rel = spec.path.name
            out.append(
                f"{rel}: \"{decision.text[:70]}\" has no `Instead of` — if nothing was rejected, "
                f"this is a Behaviour rule or a scope note, not a decision"
            )

    for i, (spec_a, dec_a) in enumerate(flat):
        for spec_b, dec_b in flat[i + 1:]:
            if spec_a.id == spec_b.id:
                continue
            ratio = difflib.SequenceMatcher(None, dec_a.text.lower(), dec_b.text.lower()).ratio()
            if ratio >= DUPLICATE_RATIO:
                out.append(
                    f"same decision in two specs ({ratio:.0%} similar): `{spec_a.id}` and "
                    f"`{spec_b.id}` both state \"{dec_a.text[:60]}\" — one spec owns it, the "
                    f"other links"
                )

    return out


SPEC_CHECKS = Path(".agents") / ".cache" / "spec-checks.json"


def load_spec_checks(repo_root: Path) -> dict[str, dict]:
    """The last `spec-sync-with-code` run per spec id, recorded by its `record_check.py` — {} when there's none."""
    path = repo_root / SPEC_CHECKS
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def check_note(check: dict | None) -> str:
    """` — last checked 2026-09-14: tests 46/47 passed; differs: retry count`, or "" with no check recorded."""
    if not isinstance(check, dict):
        return ""
    passed, failed = int(check.get("passed") or 0), int(check.get("failed") or 0)
    parts = [f"tests {passed}/{passed + failed} passed"] if passed + failed else ["no tests run"]
    if check.get("differs"):
        parts.append("differs: " + ", ".join(check["differs"]))
    if check.get("cant_tell"):
        parts.append("can't tell: " + ", ".join(check["cant_tell"]))
    if not check.get("differs") and not check.get("cant_tell"):
        parts.append("reading holds")
    return f" — last checked {check.get('date', '?')}: " + "; ".join(parts)


def find_stale(specs: list[Spec], repo_root: Path) -> list[str]:
    """Specs whose owned code has moved on since the spec last did.

    AGENTS.md opens with "specs hold intent, code holds behaviour, when they disagree stop and
    reconcile" — and nothing else in this toolchain could tell you they might. Everything else here
    checks a spec's structure. None of that notices a spec whose prose quietly stopped being true.

    `updated:` is read as "the day someone last confirmed this spec against its code", so the
    signal is commits to the owned globs dated after it. It's a prompt to look, never a failure:
    plenty of commits move code without moving intent, and a broad `owns` glob will surface often
    — which is itself worth knowing, since it usually means the spec is too broad or nobody has
    re-read it in a while. Returns [] when git can't answer, rather than guessing.
    """
    out: list[str] = []
    checks = load_spec_checks(repo_root)

    for spec in specs:
        if not spec.owns:
            continue
        note = check_note(checks.get(spec.id))
        rel = spec.path.relative_to(repo_root).as_posix()
        if not spec.updated:  # optional — nothing to judge staleness against
            continue

        command = [
            "git", "-C", str(repo_root), "log", "--format=%cd", "--date=short",
            # Strictly later days only: `updated:` has day granularity, so a spec confirmed the
            # same day as the commit it describes is current, not behind.
            f"--since={spec.updated} 23:59:59", "--",
            *(f":(glob){pattern}" for pattern in spec.owns),
        ]
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=30)
        except (OSError, subprocess.SubprocessError):
            return out
        if result.returncode != 0:
            continue

        commits = [line for line in result.stdout.splitlines() if line.strip()]
        if commits:
            out.append(
                f"{rel}: {len(commits)} commit(s) to the code it owns since `updated: "
                f"{spec.updated}` (latest {commits[0]}) — `spec-sync-with-code` can confirm it{note}"
            )

    return out


def validate(
    specs: list[Spec], changes: list[Change], repo_root: Path
) -> tuple[list[str], list[str], list[str], list[str], list[str]]:
    """Returns (errors, warnings, gaps, decision_problems, stale).

    Errors are structural: a dangling glob, a duplicate id, a cycle, ambiguous ownership, a change
    spec file that can't land. These drive --check's exit code. Everything else is a warning or
    informational — gaps especially: "no spec here yet" is the normal state of most of a
    pre-existing codebase, and coverage grows one task at a time.
    """
    errors: list[str] = []
    by_id: dict[str, Spec] = {}

    for spec in specs:
        rel = spec.path.relative_to(repo_root).as_posix()
        if spec.id in by_id:
            other = by_id[spec.id].path.relative_to(repo_root).as_posix()
            errors.append(f"duplicate id '{spec.id}': {rel} and {other}")
        else:
            by_id[spec.id] = spec

    roots = [s for s in specs if s.parent is None]
    if len(roots) > 1:
        names = ", ".join(sorted(s.id for s in roots))
        errors.append(f"multiple root specs (parent: null): {names} — exactly one expected")
    if not roots and specs:
        errors.append("no root spec — one spec must have `parent: null`")

    # A spec moved into an open change is still a valid parent or related target.
    known = set(by_id) | {s.spec_id for c in changes for s in c.specs if s.spec_id}
    for spec in specs:
        rel = spec.path.relative_to(repo_root).as_posix()

        if spec.parent and spec.parent not in known:
            errors.append(f"{rel}: parent '{spec.parent}' is not a known spec id")

        # `related` is a real pointer, not decoration — a dangling one sends a reader to a spec
        # that was never written, or was renamed without this reference following.
        for ref in spec.related:
            if ref not in known:
                errors.append(f"{rel}: related '{ref}' is not a known spec id")

        # cycle detection
        seen, cursor = {spec.id}, spec.parent
        while cursor and cursor in by_id:
            if cursor in seen:
                errors.append(f"{rel}: parent chain forms a cycle at '{cursor}'")
                break
            seen.add(cursor)
            cursor = by_id[cursor].parent

        for pattern in spec.owns:
            if not any(repo_root.glob(pattern)):
                errors.append(f"{rel}: owns '{pattern}' matches nothing on disk")

    # overlapping globs of identical specificity
    claims: list[tuple[str, Spec]] = [(p, s) for s in specs for p in s.owns]
    for i, (pattern_a, spec_a) in enumerate(claims):
        for pattern_b, spec_b in claims[i + 1:]:
            if spec_a.id == spec_b.id:
                continue
            if glob_specificity(pattern_a) != glob_specificity(pattern_b):
                continue
            overlap = set(repo_root.glob(pattern_a)) & set(repo_root.glob(pattern_b))
            if overlap:
                errors.append(
                    f"ambiguous ownership: '{pattern_a}' ({spec_a.id}) and "
                    f"'{pattern_b}' ({spec_b.id}) both claim the same files at equal specificity"
                )

    # unowned source — a gap, not an error. See find_gaps' docstring.
    gaps = find_gaps(specs, repo_root, [p for c in changes for s in c.specs if s.new for p in s.owns])

    change_errors, warnings = validate_changes(changes, by_id, repo_root)
    errors.extend(change_errors)

    return errors, warnings, gaps, find_decision_problems(specs), find_stale(specs, repo_root)


# --------------------------------------------------------------------------- render


def render_tree(specs: list[Spec], changes: list[Change], specs_dir: Path) -> str:
    # Links are relative to specs_dir, not repo_root: INDEX.md lives inside specs_dir, and a
    # markdown relative link resolves against the file that contains it, not the repo root.
    by_parent: dict[str | None, list[Spec]] = {}
    for spec in specs:
        by_parent.setdefault(spec.parent, []).append(spec)

    lines: list[str] = []

    def walk(parent: str | None, depth: int) -> None:
        for spec in sorted(by_parent.get(parent, []), key=lambda s: s.path.name):
            rel = spec.path.relative_to(specs_dir).as_posix()
            lines.append(f"{'  ' * depth}- [`{spec.id}`]({rel}) — {spec.title}")
            walk(spec.id, depth + 1)

    walk(None, 0)

    known = {s.id for s in specs}
    in_changes = {s.spec_id for c in changes for s in c.specs}
    orphans = [s for s in specs if s.parent and s.parent not in known]
    for spec in orphans:
        rel = spec.path.relative_to(specs_dir).as_posix()
        note = "parent in an open change" if spec.parent in in_changes else "orphan: unknown parent"
        lines.append(f"- [`{spec.id}`]({rel}) — {spec.title} _({note})_")

    return "\n".join(lines) or "_No specs yet._"


def render_routes(specs: list[Spec], changes: list[Change], specs_dir: Path) -> str:
    # See render_tree: links are relative to specs_dir, where INDEX.md itself lives.
    copies: dict[Path, list[str]] = {}
    for c in changes:
        for s in c.specs:
            if s.landing is not None:
                copies.setdefault(s.landing.path, []).append(
                    f"[`{c.path.name}`]({spec_file_link(c, s, specs_dir)})")

    def link(spec: Spec) -> str:
        own = f"[`{spec.id}`]({spec.path.relative_to(specs_dir).as_posix()})"
        return own + (f" (copy in {', '.join(copies[spec.path])})" if spec.path in copies else "")

    rows: list[tuple[str, str, str | None]] = [(p, link(s), s.parent) for s in specs for p in s.owns]
    # A spec in a change routes its code there until it is merged.
    rows += [
        (p, f"[`{s.spec_id}` (in a change)]({spec_file_link(c, s, specs_dir)})", s.parent)
        for c in changes for s in c.specs if s.new and s.spec_id for p in s.owns
    ]
    rows.sort(key=lambda r: glob_specificity(r[0]), reverse=True)

    if not rows:
        return "_No spec declares an `owns` glob yet._"

    out = ["| Code path | Spec | Parent |", "|---|---|---|"]
    for pattern, cell, parent in rows:
        parent_cell = f"`{parent}`" if parent else "—"
        out.append(f"| `{pattern}` | {cell} | {parent_cell} |")
    return "\n".join(out)


def spec_order(specs: list[Spec], specs_dir: Path) -> tuple[list[Spec], dict[str, str]]:
    """The tree's own reading order (root first, then depth), plus each spec's link target.

    Cross-cutting decisions in the architecture spec then sit above the feature-scoped ones that
    assume them.
    """
    by_id = {s.id: s for s in specs}
    depth_of: dict[str, int] = {}

    def depth(spec: Spec) -> int:
        if spec.id not in depth_of:
            seen: set[str] = set()
            d, cursor = 0, spec.parent
            while cursor and cursor in by_id and cursor not in seen:
                seen.add(cursor)
                d += 1
                cursor = by_id[cursor].parent
            depth_of[spec.id] = d
        return depth_of[spec.id]

    ordered = sorted(specs, key=lambda s: (depth(s), s.path.name))
    return ordered, {s.id: s.path.relative_to(specs_dir).as_posix() for s in specs}


def render_decisions(
    specs: list[Spec], changes: list[Change], specs_dir: Path, problems: list[str], open_count: int
) -> str:
    ordered, link = spec_order(specs, specs_dir)

    def cell(decision: Decision) -> str:
        # Notes that change whether a decision still binds belong next to it, not in a footnote.
        notes = []
        if decision.revisit_when:
            notes.append(f"⟳ revisit when {decision.revisit_when}")
        if decision.replaced:
            when = f" {decision.replaced_date}" if decision.replaced_date else ""
            notes.append(f"↩ replaced{when}: {decision.replaced}")
        return "<br>".join([decision.text] + [f"_{n}_" for n in notes])

    # One section per spec, so a task reads the specs it touches rather than the whole tree.
    def group(heading: str, decisions: list[Decision]) -> str:
        rows = [f"| {cell(d)} | {d.instead_of or '—'} | {d.because or '—'} |" for d in decisions]
        return "\n".join([heading, "", "| Decision | Instead of | Because |", "|---|---|---|"] + rows)

    groups = [group(f"### [`{s.id}`]({link[s.id]})", s.decisions) for s in ordered if s.decisions]
    decisions = "\n\n".join(groups) if groups else "_No decisions recorded yet._"

    pending_groups = [
        group(f"### `{s.spec_id or s.file}` — in [`changes/{c.name}`]({c.link(specs_dir)})",
              s.pending_decisions())
        for c in changes
        for s in c.specs
        if s.pending_decisions()
    ]
    # Not binding until merged, but the same "don't re-decide it" reason to read them applies.
    pending = (
        "\n\n## In open changes\n\nSpecs moved into a change, and new ones. A moved spec's decisions "
        "still bind; what the change adds binds once it merges, and is worth knowing before proposing "
        "anything in the same area.\n\n"
        + "\n\n".join(pending_groups)
        if pending_groups
        else ""
    )

    hygiene = (
        "\n## Needs attention\n\nInformational — each needs a human read, none fails `--check`.\n\n"
        + "\n".join(f"- {p}" for p in problems)
        + "\n"
        if problems
        else ""
    )

    open_pointer = (
        f"{open_count} question(s) are still open: [`OPEN-QUESTIONS.md`](OPEN-QUESTIONS.md)."
        if open_count
        else "No open questions anywhere in the tree."
    )

    return f"""{HEADER}

# Decisions

Every decision in the spec tree, and what each one rejected, one section per spec in tree order. A
spec's own Decisions come with reading it; read the sections for its parent chain and `related`
specs here. Generated — edit the owning spec, not this file.

## Decisions

{decisions}{pending}

{open_pointer}
{hygiene}"""


def render_questions(specs: list[Spec], changes: list[Change], specs_dir: Path) -> str:
    """The other half of what the code can't tell you, kept separate because it's read differently.

    A decision binds anyone proposing anything nearby. An open question binds whoever touches the
    spec that holds it — and a spec's own questions already come with reading it, so this file is
    the view across the tree, grouped by spec so it stays readable as coverage grows.
    """
    ordered, link = spec_order(specs, specs_dir)

    def group(heading: str, questions: list[OpenQuestion]) -> str:
        rows = [f"| {q.text} | {q.action or '—'} |" for q in questions]
        return "\n".join([heading, "", "| Question | Action |", "|---|---|"] + rows)

    groups = []
    for s in ordered:
        still_open = [q for q in s.questions if not q.resolved]
        if still_open:
            groups.append(group(f"## [`{s.id}`]({link[s.id]})", still_open))
    for c in changes:
        where = f"[`changes/{c.name}`]({c.link(specs_dir)})"
        for s in c.specs:
            if s.pending_questions():
                groups.append(group(f"## `{s.spec_id or s.file}` — in {where}", s.pending_questions()))
    questions = "\n\n".join(groups) if groups else "_Nothing open._"

    resolved_count = sum(1 for s in specs for q in s.questions if q.resolved)
    resolved_note = (
        f"\n\n{resolved_count} resolved question(s) are kept in place in their own specs, struck "
        f"through, and are not listed here."
        if resolved_count
        else ""
    )

    return f"""{HEADER}

# Open questions

Every unresolved question in the spec tree and in open changes, one section per spec. A spec's own
questions come with reading it —
this is the view across the tree. Generated — edit the owning spec or change, not this file.

{questions}{resolved_note}
"""


def summarise_gaps(gaps: list[str]) -> str:
    """The area names alone. The uncovered files under each are the skill's output."""
    return ", ".join(f"`{g.split(chr(39))[1]}`" if "'" in g else f"`{g}`" for g in gaps)


def render_index(
    specs: list[Spec],
    changes: list[Change],
    errors: list[str],
    gaps: list[str],
    stale_specs: list[str],
    specs_dir: Path,
) -> str:
    drift = (
        "\n".join(f"- {e}" for e in errors)
        if errors
        else "_None. Every spec resolves and no ownership is ambiguous._"
    )
    # Both lists below are summarised, not printed. This file is read on every task for routing,
    # and neither list is routing data — it's a work queue, which `spec-rebuild-overviews` already prints in
    # full every time it runs. The counts are what a reader needs at routing time: whether the
    # spec they are about to open is one of the affected ones.
    coverage = (
        f"{len(gaps)} area(s) have no owning spec yet — normal.\n\n"
        f"{summarise_gaps(gaps)}"
        if gaps
        else "_Everything is covered._"
    )
    freshness = (
        f"{len(stale_specs)} spec(s) own code that has been committed to since the spec itself was "
        f"last confirmed. A prompt to check, not a defect — code moves without intent moving. "
        f"`spec-sync-with-code` can confirm one: a clean check bumps `updated:`, anything else shows here "
        f"as its last result.\n\n"
        + "\n".join(f"- {s}" for s in stale_specs)
        if stale_specs
        else "_Every spec with an `owns` glob is at least as recent as the code under it._"
    )
    violated = {
        s.path.relative_to(specs_dir).as_posix(): len(s.violations) for s in specs if s.violations
    }
    violations = (
        f"{sum(violated.values())} Behaviour line(s) recorded as currently violated. Each goes false "
        f"silently when the code is fixed — re-check it against the code before trusting it, and "
        f"remove the note in the same change as the fix.\n\n"
        + ", ".join(f"`{p}` {n}" for p, n in sorted(violated.items()))
        + "\n\nRun `spec-rebuild-overviews` for the list."
        if violated
        else "_No Behaviour line is recorded as currently violated._"
    )
    return f"""{HEADER}

# Spec index

Code path to owning spec, most specific glob first: the first row matching your file is the owner.
A spec in `changes/` is the version being worked on.

A file matching nothing has no owning spec — normal here; see "Not yet specced" below.

## Code → spec

{render_routes(specs, changes, specs_dir)}

## Pending changes

{render_pending(changes, specs_dir)}

## Spec tree

{render_tree(specs, changes, specs_dir)}

## Drift

Structural problems, and the only findings serious enough to stop an automated check: a spec with
no `id` or `title`, a dangling `owns` glob, an unknown `parent`, a duplicate id, two specs claiming
one file, a parent cycle. Empty is the normal state.

Everything else `spec-rebuild-overviews` notices — a stale spec, a coverage gap, a misplaced `status` — it
reports and does not fail on.

{drift}

## Possibly stale

{freshness}

## Known violations

{violations}

## Not yet specced

{coverage}

Also generated: [`DECISIONS.md`](DECISIONS.md), [`OPEN-QUESTIONS.md`](OPEN-QUESTIONS.md).
"""


# --------------------------------------------------------------------------- main


def find_repo_root() -> Path:
    """The folder holding `.agents/`, found from this script's own location, so it runs from anywhere."""
    for parent in Path(__file__).resolve().parents:
        if (parent / ".agents").is_dir():
            return parent
    return Path.cwd()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--specs-dir", default=".specs")
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument("--check", action="store_true", help="exit 1 on structural drift only")
    args = parser.parse_args()

    repo_root = (args.repo_root or find_repo_root()).resolve()
    specs_dir = (repo_root / args.specs_dir).resolve()

    if not specs_dir.is_dir():
        print(f"error: {specs_dir} does not exist", file=sys.stderr)
        return 2

    specs, parse_errors, parse_warnings = load_specs(specs_dir)
    changes, change_folder_warnings = load_changes(specs_dir, specs)
    validation_errors, validation_warnings, gaps, decision_problems, stale_specs = validate(
        specs, changes, repo_root
    )
    errors = parse_errors + validation_errors
    warnings = parse_warnings + change_folder_warnings + validation_warnings

    open_count = (
        sum(1 for s in specs for q in s.questions if not q.resolved)
        + sum(len(s.pending_questions()) for c in changes for s in c.specs)
    )
    outputs = {
        specs_dir / "INDEX.md": render_index(
            specs, changes, errors, gaps, stale_specs, specs_dir
        ),
        specs_dir / "DECISIONS.md": render_decisions(
            specs, changes, specs_dir, decision_problems, open_count
        ),
        specs_dir / "OPEN-QUESTIONS.md": render_questions(specs, changes, specs_dir),
    }
    stale = [
        path for path, content in outputs.items()
        if (path.read_text(encoding="utf-8") if path.exists() else "") != content
    ]
    tasks_done = [c.name for c in changes if c.approved and c.tasks_all_done()]

    if args.check:
        # Only drift fails; everything below is informational. The generated files are kept out of git.
        for path in stale:
            print(f"({path.name} is out of date — run build_index.py; informational)", file=sys.stderr)
        for error in errors:
            print(f"drift: {error}", file=sys.stderr)
        for warning in warnings:
            print(f"warning: {warning}", file=sys.stderr)
        if gaps:
            print(f"({len(gaps)} area(s) not yet specced — informational, not a failure)",
                  file=sys.stderr)
        if stale_specs:
            print(f"({len(stale_specs)} spec(s) possibly stale — informational, not a failure)",
                  file=sys.stderr)
        n_violations = sum(len(s.violations) for s in specs)
        if n_violations:
            print(f"({n_violations} Behaviour line(s) recorded as currently violated — informational)",
                  file=sys.stderr)
        if tasks_done:
            print(f"({len(tasks_done)} approved change(s) with every task done: {', '.join(tasks_done)} "
                  f"— merge once the user says it's done)", file=sys.stderr)
        n_long = sum(len(s.long_history_rows) for s in specs)
        if n_long:
            print(f"({n_long} Change history row(s) past {HISTORY_ROW_WORDS} words — "
                  f"informational)", file=sys.stderr)
        return 1 if errors else 0

    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    written = ", ".join(p.name for p in outputs)
    print(f"wrote {written} — {len(specs)} spec(s), {len(changes)} open change(s)")
    for change in changes:
        hint = " — every task done: merge once the user says it's done" if change.name in tasks_done else ""
        print(f"  change {change.name}: {change.status()}{hint}")
    if errors:
        print(f"\n{len(errors)} drift item(s):")
        for error in errors:
            print(f"  - {error}")
    if warnings:
        print(f"\n{len(warnings)} warning(s) — none fails `--check`:")
        for warning in warnings:
            print(f"  - {warning}")
    if stale_specs:
        print(f"\n{len(stale_specs)} spec(s) possibly stale — code committed since the spec was "
              f"last confirmed:")
        for item in stale_specs:
            print(f"  - {item}")
    violations = [(s, v) for s in specs for v in s.violations]
    if violations:
        print(f"\n{len(violations)} Behaviour line(s) recorded as currently violated — re-check each "
              f"against the code:")
        for spec, item in violations:
            print(f"  - {spec.path.relative_to(repo_root).as_posix()}: {item}")
    long_rows = [(s, r) for s in specs for r in s.long_history_rows]
    if long_rows:
        print(f"\n{len(long_rows)} Change history row(s) past {HISTORY_ROW_WORDS} words — rewrite "
              f"as one sentence (spec-style-rules' *One row, one sentence*):")
        for spec, row in long_rows:
            print(f"  - {spec.path.relative_to(repo_root).as_posix()}: {row}")
    if decision_problems:
        print(f"\n{len(decision_problems)} decision item(s) needing a human read:")
        for item in decision_problems:
            print(f"  - {item}")
    if gaps:
        print(f"\n{len(gaps)} area(s) not yet specced (informational, not a failure):")
        for gap in gaps:
            print(f"  - {gap}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
